import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { PayrollResultData } from '../types';
import { formatDisplayDate } from './dateUtils';
import { formatCurrency } from './formatters';

export function generatePayslipPDF(
  result: PayrollResultData,
  periodStart: string,
  periodEnd: string
): Blob {
  const { employee, calculations } = result;
  const doc = new jsPDF();

  // Set document properties
  doc.setProperties({
    title: `Payslip - ${employee.first_name} ${employee.last_name}`,
    subject: `Pay Period: ${formatDisplayDate(periodStart)} - ${formatDisplayDate(periodEnd)}`,
    creator: 'Ask Your HR',
    author: 'Ask Your HR'
  });

  // Header
  doc.setFontSize(20);
  doc.text('PAYSLIP', doc.internal.pageSize.width / 2, 20, { align: 'center' });
  
  doc.setFontSize(12);
  doc.text(`Pay Period: ${formatDisplayDate(periodStart)} - ${formatDisplayDate(periodEnd)}`, 
    doc.internal.pageSize.width / 2, 30, { align: 'center' });

  // Employee Details
  (doc as any).autoTable({
    startY: 40,
    head: [['Employee Details', '']],
    body: [
      ['Name', `${employee.first_name} ${employee.last_name}`],
      ['Email', employee.email],
      ['Tax Code', employee.tax_code],
      ['Employment Type', employee.employment_type === 'salary' ? 'Salaried' : 'Hourly'],
      employee.kiwisaver_enrolled ? 
        ['KiwiSaver Rate', `${employee.kiwisaver_rate}%`] : 
        ['KiwiSaver', 'Not Enrolled']
    ],
    theme: 'grid',
    headStyles: { fillColor: [75, 85, 99] },
    styles: { fontSize: 10 }
  });

  // Earnings
  (doc as any).autoTable({
    startY: (doc as any).lastAutoTable.finalY + 10,
    head: [['Earnings', 'Amount']],
    body: [
      ['Gross Pay', formatCurrency(calculations.grossPay)]
    ],
    theme: 'grid',
    headStyles: { fillColor: [75, 85, 99] }
  });

  // Deductions
  const deductions = [
    ['PAYE Tax', formatCurrency(calculations.payeTax)]
  ];

  if (employee.kiwisaver_enrolled) {
    deductions.push([
      `KiwiSaver (${employee.kiwisaver_rate}%)`,
      formatCurrency(calculations.kiwiSaverDeduction)
    ]);
  }

  (doc as any).autoTable({
    startY: (doc as any).lastAutoTable.finalY + 10,
    head: [['Deductions', 'Amount']],
    body: deductions,
    theme: 'grid',
    headStyles: { fillColor: [75, 85, 99] }
  });

  // Employer Contributions
  if (employee.kiwisaver_enrolled) {
    (doc as any).autoTable({
      startY: (doc as any).lastAutoTable.finalY + 10,
      head: [['Employer Contributions', 'Amount']],
      body: [
        ['KiwiSaver (3%) - Not deducted from pay', formatCurrency(calculations.employerKiwiSaver)]
      ],
      theme: 'grid',
      headStyles: { fillColor: [75, 85, 99] }
    });
  }

  // Net Pay
  (doc as any).autoTable({
    startY: (doc as any).lastAutoTable.finalY + 10,
    head: [['Net Pay', 'Amount']],
    body: [['Total', formatCurrency(calculations.netPay)]],
    theme: 'grid',
    headStyles: { fillColor: [75, 85, 99] },
    styles: { fontStyle: 'bold', fontSize: 11 }
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128);
  doc.text(
    `Generated by Ask Your HR on ${new Date().toLocaleString()}`,
    doc.internal.pageSize.width / 2,
    doc.internal.pageSize.height - 10,
    { align: 'center' }
  );

  return doc.output('blob');
}

export function generatePayslipCSV(
  result: PayrollResultData,
  periodStart: string,
  periodEnd: string
): string {
  const { employee, calculations } = result;
  
  const rows = [
    ['PAYSLIP'],
    ['Pay Period', `${formatDisplayDate(periodStart)} - ${formatDisplayDate(periodEnd)}`],
    [''],
    ['EMPLOYEE DETAILS'],
    ['Name', `${employee.first_name} ${employee.last_name}`],
    ['Email', employee.email],
    ['Tax Code', employee.tax_code],
    ['Employment Type', employee.employment_type === 'salary' ? 'Salaried' : 'Hourly'],
    ['KiwiSaver', employee.kiwisaver_enrolled ? `${employee.kiwisaver_rate}%` : 'Not Enrolled'],
    [''],
    ['EARNINGS', 'Amount'],
    ['Gross Pay', formatCurrency(calculations.grossPay)],
    [''],
    ['DEDUCTIONS', 'Amount'],
    ['PAYE Tax', formatCurrency(calculations.payeTax)]
  ];

  if (employee.kiwisaver_enrolled) {
    rows.push([`KiwiSaver (${employee.kiwisaver_rate}%)`, formatCurrency(calculations.kiwiSaverDeduction)]);
    rows.push(['']);
    rows.push(['EMPLOYER CONTRIBUTIONS', 'Amount']);
    rows.push(['KiwiSaver (3%) - Not deducted from pay', formatCurrency(calculations.employerKiwiSaver)]);
  }

  rows.push(['']);
  rows.push(['NET PAY', 'Amount']);
  rows.push(['Total', formatCurrency(calculations.netPay)]);
  rows.push(['']);
  rows.push([`Generated by Ask Your HR on ${new Date().toLocaleString()}`]);

  return rows.map(row => row.join(',')).join('\n');
}